name: Release Binaries

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux
          - os: macOS-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - uses: actions/checkout@v4

      - name: Setup target
        run: rustup target add ${{ matrix.target }}

      - name: Install musl
        run: sudo apt-get install musl-tools
        if: contains(matrix.target, 'linux-musl')

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release --verbose

      - name: Run tests
        run: cargo test --verbose